version: '3'

services:
  api:
    build: .
    volumes:
      - ./:/var/www/html/
    working_dir: /var/www/html
    ports:
      - 8000:80
      - 444:443
    extra_hosts:
      - "localhost:127.0.0.1"
    networks:
      - v1_default

networks:
  v1_default:
    external:
      name: octopus_default
